package sample;
// Generated 2021/01/14 13:40:28 by Hibernate Tools 5.4.21.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private UserId id;

	public User() {
	}

	public User(UserId id) {
		this.id = id;
	}

	public UserId getId() {
		return this.id;
	}

	public void setId(UserId id) {
		this.id = id;
	}

}
